### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Gandalf360one** [DungeonDev/SpigotAccurateBlockPlacement#1]
Doesnt work anymore in mc 1.21 pls update if pos

Mc version: 1.21
Mc-Server: paper
Tweakertoo: latest
Protocollob: latest
SpigotAccurateBlockPlacement: latest

log: https://pastebin.com/cX3V3z8r

**Comment by DungeonDev** [comment]
I can't seem to get protocollib working correctly with 1.21. Here's a version without it where I manually intercepting packets instead. I've only tested it on paper, try it out and see if it works for you as well.
[PaperAccurateBlockPlacement-1.1.0-SNAPSHOT-dev.zip](https://github.com/user-attachments/files/16627413/PaperAccurateBlockPlacement-1.1.0-SNAPSHOT-dev.zip)

**Comment by Gandalf360one** [comment]
Thank you very much!
I is working perfectly.
I m using paper too btw :D
